Rake::TaskManager.record_task_metadata = true
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
require 'csv'
require_relative 'config/application'



Rails.application.load_tasks
